eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:2022/eureka
server:
  port: 2020
spring:
  application:
    name: Sango-Gateway
  cloud:
    gateway:
      routes:
        - id: Sango-User  #路由id
          uri: lb://Sango-User #lb 从Eureka中获取具体的服务
          predicates: #路由断言：可以匹配映射路径
            - Path=/user/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306
    username: root
    password: Shx20020810
    hikari:
      max-lifetime: 120000