spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306
    username: root
    password: Shx20020810
    hikari:
      max-lifetime: 120000
    profiles:
      active: dev
server:
  port: 2023
mybatis:
  configuration:
    map-underscore-to-camel-case: true # enable underscore to camel case
    call-setters-on-nulls: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.fantasy.sangoserver.mapper