spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://43.138.74.153:1433;encrypt=true;trustServerCertificate=true
    username: sa
    password: Shx20020810
    hikari:
      max-lifetime: 120000
server:
  port: 2023
mybatis:
  configuration:
    map-underscore-to-camel-case: true # enable underscore to camel case
    call-setters-on-nulls: true
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.fantasy.sangoserver.mapper